language: java

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2
  
script:
- mvn package -Dmaven.javadoc.skip=true -B -V
- ls -la all/target

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
    
