/*
 * ====================================================================
 * Copyright (c) 2008 JavaGit Project.  All rights reserved.
 *
 * This software is licensed using the GNU LGPL v2.1 license.  A copy
 * of the license is included with the distribution of this source
 * code in the LICENSE.txt file.  The text of the license can also
 * be obtained at:
 *
 *   http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
 *
 * For more information on the JavaGit project, see:
 *
 *   http://www.javagit.com
 * ====================================================================
 */
package edu.nyu.cs.javagit.api.responses;

import java.util.ArrayList;
import java.util.List;

/**
 * Response data object obtained from git-add command. It contains a list of file-action pair that
 * contains the list of files that are added by the git-add command.
 * <p/>
 * The output can also be generated by "-n" option of git-add command ( dry run ). So we have two
 * Actions for git-add command - add - for adding a file to the repository dry run - for just
 * testing the output of the command. Dry run info need to be passed back so that the receiver of
 * this object knows that the command did not actually run and was just a dry run. The git-add
 * commands that return no output will return this object with filesAdded list as empty-list.
 */
public class GitAddResponse extends AbstractResponse {

    private final List<String> addedFiles = new ArrayList<String>();

    public void addFile(String file) {
        addedFiles.add(file);
    }

    public List<String> getAddedFiles() {
        return addedFiles;
    }
}
